replicas: 2

initImage:
  registry: quay.io
  name: giantswarm/debug
  tag: master
  pullPolicy: IfNotPresent

image:
  registry: quay.io
  name: giantswarm/cloudflared
  tag: 2022.8.4-amd64
  pullPolicy: IfNotPresent

deployment:
  annotations: {}

accountEmail: ""
accountId: ""
apiKey: ""
apiKeySecretName: ""
tunnelSecretBase64: ""
tunnelSecretName: ""

useExistingTunnels:
  enabled: false
  credentialsSecretName: ""
  tunnel: ""

useQuickTunnel: false

config:
  no-tls-verify: false
  loglevel: "info"
  transport-loglevel: "info"

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "100Mi"
    cpu: "100m"

global:
  podSecurityStandards:
    enforced: false
