{{- if and (not .Values.apiKeySecretName) (eq .Values.useExistingTunnels.enabled false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "cloudflared.fullname" . }}-apikey"
type: Opaque

data:
  apiKey: {{ required "ERR: apiKey or apiKeySecretName is required" .Values.apiKey | b64enc }}
{{- end -}}
