{{- if not .Values.apiKeySecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "cloudflared-{{ .Release.Name }}-apikey"
type: Opaque

data:
  apiKey: {{ required "ERR: apiKey or apiKeySecretName is required" .Values.apiKey | b64enc }}
{{- end -}}
