{{- if not .Values.useExistingTunnels.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "cloudflared.fullname" . }}-helm-pre-delete"
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "cloudflared.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-{{ .Release.Name }}"
      restartPolicy: Never
      containers:
      - name: clean-delete-tunnel
        image: {{ .Values.initImage.registry }}/{{ .Values.initImage.name }}:{{ .Values.initImage.tag }}
        imagePullPolicy: {{ .Values.initImage.pullPolicy }}
        securityContext:
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        {{- include "clean+delete-argo-tunnel-command" . | nindent 8 }}
        env:
          {{- include "create_tunnel.envs" . | nindent 10 }}
...
{{- end }}
