{{- if not .Values.useExistingTunnels.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "cloudflared-{{ .Release.Name }}"
type: Opaque

data:
  accountEmail: {{ required "ERR: accountEmail is required" .Values.accountEmail | b64enc }}
  accountId: {{ required "ERR: accountId is required" .Values.accountId | b64enc }}
{{- end -}}
