{{- if and (not .Values.useExistingTunnels.enabled) (not .Values.useQuickTunnel) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudflared.fullname" . }}
type: Opaque

data:
  accountEmail: {{ required "ERR: accountEmail is required" .Values.accountEmail | b64enc }}
  accountId: {{ required "ERR: accountId is required" .Values.accountId | b64enc }}
{{- end -}}
