{{- if and (not .Values.tunnelSecretName) (not .Values.useExistingTunnels.enabled) (not .Values.useQuickTunnel) }}
{{- $tunnelSecretName := include "cloudflared.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "{{ $tunnelSecretName }}-tunnelsecret" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudflared.fullname" . }}-tunnelsecret
type: Opaque

stringData:
  {{- if hasKey $secret "data.tunnelSecret" -}}
  tunnelSecret: {{ $secret.data.tunnelSecret }}
  {{- else }}
  tunnelSecret: {{ .Values.tunnelSecretBase64 | default (uuidv4 | b64enc) | quote }}
  {{ end }}
{{- end }}
