{{- if or (not .Values.tunnelSecretName) (not .Values.useExistingTunnels.enabled) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cloudflared-{{ .Release.Name }}-tunnelsecret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: "cloudflared-{{ .Release.Name }}-tunnelsecret"
type: Opaque

stringData:
  {{- if hasKey $secret "data.tunnelSecret" -}}
  tunnelSecret: {{ $secret.data.tunnelSecret }}
  {{- else }}
  tunnelSecret: {{ .Values.tunnelSecretBase64 | default (uuidv4 | b64enc) | quote }}
  {{ end }}
{{- end }}
